---
name: Check if music video URLs are valid once per month.

on:
  # 2am of the 15th:
  schedule:
    - cron: "0 2 15 * *"

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
