name: Automated sanity tests.

on: [push, pull_request]

jobs:
  video-exists-test:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    strategy:
      matrix:
        python-versions: [ '3.10' ]
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-versions }}.
        uses: actions/setup-python@v3
        with:
          python-versions: ${{ matrix.python-versions }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Get changed files.
        id: changed-files
        uses: tj-actions/changed-files@v22.1

      - name: List all changed files.
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo ">>> $file was changed."
          done

      - name: Check if List.md changed.
        if: contains(steps.changed-files.outputs.modified_files, 'List.md')
        run: echo ">>> Music video list modified!"

      - name: Verify URLs are valid and videos exist.
        env: 
          GOOGLEAPIYOUTUBEKEY: ${{ secrets.GOOGLEAPIYOUTUBEKEY }}
        run: |
          #pytest -vvv tests/test_videos_exist.py 
          python tests/debug_manual_tests.py # TODO: execute this IF pytest fails.
